apiVersion: k3d.io/v1alpha2
kind: Simple
name: mycluster
image: rancher/k3s:v1.24.3-k3s1
servers: 1
agents: 2
ports:
- port: 80:80
  nodeFilters:
  - loadbalancer
- port: 443:443
  nodeFilters:
  - loadbalancer
- port: 4443:4443
  nodeFilters:
  - loadbalancer
volumes:
  - volume: /opt/k3dvol:/opt/k3dvol
options:
  k3s:
    extraServerArgs:
    - --no-deploy=traefik