apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/adguardhome/certs/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: adguard-home
  namespace: default
  labels:
    app: adguard-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      containers:
      - name: adguard-home
        image: adguard/adguardhome:latest
        volumeMounts:
        - name: config-volume
          mountPath: /opt/adguardhome/certs
      volumes:
      - name: config-volume
        persistentVolumeClaim:
        claimName: adguard-pvc