---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-test
  name: app-test
  namespace: app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-test
  template:
    metadata:
      labels:
        app: app-test
    spec:
      containers:
      - image: nginx
        name: app-test
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app-test
  namespace: app-test
  labels:
    app: app-test
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: app-test
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: app-test-redirect-scheme
  namespace: app-test
spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: "443"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: app-test-http
  namespace: app-test
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`app-test.local`)
      kind: Rule
      middlewares:
        - name: app-test-redirect-scheme      
      services:
        - name: app-test
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: app-test-https
  namespace: app-test
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`app-test.local`)
      kind: Rule     
      services:
        - name: app-test
          port: 80
  tls:
    certResolver: pebble
#    certResolver: letsencrypt
